### ISSUE TITLE
USER STORY: Add media to workouts posted

### ISSUE THREAD

**Issue by Oile995** [Oile995/Project4#10]
As a **Site User** I can **upload videos and images reflecting the workouts** so that **others can have an easier time understanding the different movements in the exercises**

**Acceptance Criteria**

- User should be able to click media box + to add Image to exercise when creating a workout
- Media should follow the aspect ratio of the media box
- Workout need to be approved by admin before publicly posted

**Tasks**

- [x] Task 1: Update Workout model for exercise media
- [x] Task 2: Update template and view to display uploaded media
- [x] Task 3: Update CSS to display media per aspect ratio of the media container.
- [x] Task 4: Test the completed functionality

**Comment by Oile995** [comment]
Added Cloudinary image field in model
Added to template of exercise option to add images
Updated css so image fit container
Tested multiple different uploads, in different orders and sizes. Checked in view post creations and fixed all visual bugs.


![Image](https://github.com/Oile995/Project4/assets/11351866/0394c807-9680-4179-be01-4a32baf09c71)



![Image](https://github.com/Oile995/Project4/assets/11351866/54c801b2-d166-4729-8a4e-b0d0a0bde8b9)
