### ISSUE TITLE
USER STORY: Edit Workouts and Exercises

### ISSUE THREAD

**Issue by Oile995** [Oile995/Project4#11]
As a **User** I can **Edit already created Workouts** so that **I can change the Workout details, pictures if needed**

**Acceptance Criteria**

- Authenticator check and if user is eligible to update
- Open workout update form from Workout detail page

**Tasks**

- [x] Task 1: Add update Workout view and html + css
- [x] Task 2: Add update Exercise view and html + css
- [x] Task 3: Add authentication and eligibility ifs to access  update
- [x] Task 3: Test the completed functionality

**Comment by Oile995** [comment]
Created chained views for both Workout and then Exercise
Added authentication and eligibility ifs to views
Tested functionality without issues.

![Image](https://github.com/Oile995/Project4/assets/11351866/d7506705-2a75-40a8-9dcd-05e3e3fcf32a)
