### ISSUE TITLE
USER STORY: View Workout

### ISSUE THREAD

**Issue by Oile995** [Oile995/Project4#13]
As a **User** I can **open workouts from home screen** so that **view the workout details and review the exercises**

**Acceptance Criteria**
- As a site user, I can click the workout link and review the different exercises in the details page
- Each Exercise is shown in a list with checkboxes for each step on the left side and details window on the right corresponding.

**Tasks**

- [x] Task 1: Create Workout details view
- [x] Task 2: Create workout details template
- [x] Task 3: Customize HTML and CSS to make page reflect wireframe
- [x] Task 4: Test that workout exercises are shown per wireframe without errors

**Comment by Oile995** [comment]
Created view for Workout details and 
reused corresponding html from https://github.com/Code-Institute-Solutions/Django3blog
Updated HTML and CSS to fit project Wireframes.
Tested view in different sizes and different workouts

![Image](https://github.com/Oile995/Project4/assets/11351866/188be6a4-74f3-491b-85e2-84e27eca0b12)
