### ISSUE TITLE
USER STORY: Delete Workout

### ISSUE THREAD

**Issue by Oile995** [Oile995/Project4#14]
As a **User** I can **Delete workouts that I have created** so that **If I make a mistake or want to remove workout, I can without admins help**

**Acceptance Criteria**

- Authenticator check and if user is eligible to delete
- Open workout delete form from Workout detail page

**Tasks**

- [x] Task 1: Add delete Workout view and html + css
- [x] Task 2: Add delete Exercise view and html + css
- [x] Task 3: Add authentication and eligibility ifs to access  delete
- [x] Task 3: Test the completed functionality

**Comment by Oile995** [comment]
Added Delete view for workout and its children
Reused and update function from https://github.com/leonardo-simeone/venezuelan-food-cookbook
Added checks for authentication and eligibility
Tested as different users without issues

![Image](https://github.com/Oile995/Project4/assets/11351866/b703a820-e725-43af-8671-d98e467c4034)
