### ISSUE TITLE
USER STORY: Use workout

### ISSUE THREAD

**Issue by Oile995** [Oile995/Project4#2]
As a **Site User** I can **start a workout** so that **I can keep track of the exercise checkbox and workout tracking. **

**Acceptance Criteria**

- User have to be registered and logged in
- User must start workout for timer to start
- User must click each checkbox for each exercise completed
- Once complete workout is clicked, time spent and history of workout is saved under user page.

**Tasks**

- [ ] Task 1: Add function that checks if user is signed-in
- [x] Task 2: Add visual update that Exercise is done
- [ ] Task 3: Add function that tracks start and stop date
- [ ] Task 4: Store time spent and workout id with incrementing variable in user details
- [x] Task 5: Test the completed functionality

**Comment by Oile995** [comment]
Added Checkbox option for each Exercise.
Did not implement tracker of user data or authenticator as it fell under statistics which ended up being NITH
And a future feature.
Tested checkbox option

![Image](https://github.com/Oile995/Project4/assets/11351866/2154d1ba-1a8f-4215-8387-29bf6fc32ff5)
