### ISSUE TITLE
USER STORY: Create and post workouts as a registered user

### ISSUE THREAD

**Issue by Oile995** [Oile995/Project4#3]
As a **Site User/Admin** I can **create and post my own workout** so that **I and others can use my workout routine**

**Acceptance Criteria**

- User have to be registered and logged in
- User must create minimum 3 exercises
- Each exercise must have instructions(20 char min)
- Workout must have Title (10char min) Description(20char min)

**Tasks**

- [x] Task 1: Add button in nav-bar for creating new workout(Requesting login if not already logged in)
- [x] Task 2: Design HTML and CSS for workout creation page, with fields: Exercises, Instructions and two media blocks
- [x] Task 3: Create the code for model, viewer and controller
- [x] Task 4: Test the completed functionality

**Comment by Oile995** [comment]
Added button in navbar linking to view function
Created Workout and Exercise form and then view of both
Chained the view from Workout to Exercises based on how many selected in Workout form
Reused base html form template from https://github.com/leonardo-simeone/venezuelan-food-cookbook
Edited to fit project.
Tested as multiple different user and in admin panel without errors.

![Image](https://github.com/Oile995/Project4/assets/11351866/3fdf583d-ba47-400d-b65d-d9fd67890f9d)



![Image](https://github.com/Oile995/Project4/assets/11351866/a9b7cfcc-bf80-422f-8b31-ae56435d5fc2)
