### ISSUE TITLE
USER STORY: Account registration

### ISSUE THREAD

**Issue by Oile995** [Oile995/Project4#4]
As a **Site User** I can **register an Account** so that **I can create and use workouts posted and interact with comments and likes**

**Acceptance Criteria**

- User email is not used for previous account
- User submit a valid name and email
- User should be able to log in and out once account is created
- User should be able to access user page once logged in
- User should be able to delete account

**Tasks**

- [x] Task 1: Add logic for account registration
- [x] Task 2: Add code and logic for signup/sign-in/sign-out button in navbar
- [ ] Task 3: Add button on user page for deletion of account
- [x] Task 4: Test registration, sign-in/out and deletion functionality

**Comment by Oile995** [comment]
Added allauth and html templates from https://github.com/Code-Institute-Solutions/Django3blog
Updated code to fit project.
Did not add delete function of profile.

![Image](https://github.com/Oile995/Project4/assets/11351866/8c3f17fa-bfff-45fa-b222-1334dc7ca770)
