### ISSUE TITLE
USER STORY: Track workouts

### ISSUE THREAD

**Issue by Oile995** [Oile995/Project4#5]
As a **Site User** I can **view my workout history** so that **I can keep track of past workouts**

**Acceptance Criteria**

- User have to be registered and logged in
- In user page, display statistics column with: Time spent, workouts completed integer and all time favorite workout used
- In user page, display a list of users own created workouts
- In user page, display a list of users  workout history displaying the last 5 previous workouts
- In user page, display a list of users top 3 most used workouts

**Tasks**

- [ ] Task 1: Add logic saving statistics from previous completed workouts and link to user page details
- [ ] Task 2: Design HTML and CSS to add Statistics column and the 3 lists of workouts to user page per wireframe
- [ ] Task 3: Use user details to display workouts created
- [ ] Task 4: Implement logic to display workout history and top 3 workouts
- [ ] Task 4: Test the completed functionality
