### ISSUE TITLE
USER STORY: Deploy Website

### ISSUE THREAD

**Issue by Oile995** [Oile995/Project4#6]
As a **Developer** I can **deploy this website at an early stage** so that **I can be sure that the project is deployable long before the final stage of the project**

**Acceptance Criteria**

- The project must be deployed to Heroku
- The project must use a 3rd party to host images like Cloudinary
- The code must be stored in GitHub for the assessor to grade
- The project must use a postgresSQL database

**Tasks**

- [x] Task 1: Create a repository on Github from project template
- [x] Task 2: Open project and install perquisites for the django app
- [x] Task 3: Setup environment variables 
- [x] Task 4: Create and link project with a Cloudinary account
- [x] Task 5: Create and link ElephantSQL instance to project
- [x] Task 6: Link Github repository with Heroku and deploy
- [x] Task 7: Test that the website is deployed correctly on Heroku

**Comment by Oile995** [comment]
Created the repo from Codeinstitute template and installed django with initial apps.
Created elephantSQL, cloudinary and Heroku accounts and linked to project
Created env.py and linked 3rd party programs with project
Made initial commit to github
Linked Github repository on Heroku
Deployed project and tested provided URL 

![Image](https://github.com/Oile995/Project4/assets/11351866/1863e0aa-d622-42e1-8203-5838380319c2)
