### ISSUE TITLE
USER STORY: Add Likes and Comments

### ISSUE THREAD

**Issue by Oile995** [Oile995/Project4#8]
As a **Site User** I can **Like and comment workouts** so that **I can share experience and opinion for other users**

**Acceptance Criteria**

- User have to be registered and logged in
- User must be able to click/unclick a toggle button for likes that states the amount of likes
- User must be able to add a comment to workouts

**Tasks**

- [ ] Task 1: Create form model for comment
- [ ] Task 2: Add the view to create a comment
- [ ] Task 3: Make Like button togglable 
- [ ] Task 4: Update template so only logged in users can add comments and likes
- [ ] Task 5: Test the completed functionality
