### ISSUE TITLE
USER STORY: View Likes and Comments

### ISSUE THREAD

**Issue by Oile995** [Oile995/Project4#9]
As a **Site User** I can **log in and read comments and see likes** so that **I can find the best workout for me**

**Acceptance Criteria**

- Likes are shown with a number under it reflecting amount of likes
- Comments are displayed as dropdown menu linked to workouts on home screen
- The comments are listed from oldest to newest

**Tasks**

- [ ] Task 1: Create the view code for comments and likes
- [ ] Task 2: Create a template to render the view
- [ ] Task 3: Connect the URLs
- [ ] Task 4: Update HTML and CSS for user friendly view of comments and likes 
- [ ] Task 5: Test the completed functionality
